Error handling
Cusymint/cusymint pull request #106
Opened 2022-11-17 11:49 UTC by TortillaZHawaii

2022-11-21 10:31 UTC, zh-qs requested changes
Przydałyby się jeszcze testy

2022-11-21 10:31 UTC, zh-qs commented on engine/src/Server/SolverProcessManager.cu
> +std::string exec(const std::string cmd) {
Proponuję nazwę `execute_and_read_output`, nazwa `exec` może się mylić z funkcjami z `unistd.h`

2022-11-21 10:31 UTC, zh-qs commented on engine/src/Server/SolverProcessManager.cu
> +        return R"({"errors": ["Internal runtime error."]})";
Myślę, że warto dodać jeszcze drukowanie na `stdout/stderr` dokładniejszych informacji o wyjątkach

2022-11-21 23:36 UTC, TortillaZHawaii commented
> Przydałyby się jeszcze testy

Testy integracyjne są po stronie biblioteki `cusymint_client`.

2022-11-22 11:47 UTC, zh-qs requested changes

2022-11-22 11:47 UTC, zh-qs commented on engine/src/Server/Utils.cuh
> +    if constexpr (Consts::DEBUG) {
Myślę, że warto też wypisywać komunikaty na produkcji

2022-11-22 11:50 UTC, zh-qs commented on engine/src/Server/JsonSolver.cu
> +        response_builder.add_error("Internal error");
I tutaj też fajnie by było, żeby w przypadku błędu CUDY też go jakoś zwrócić; raczej taka uwaga na przyszłość, bo przy obecnym rozwiązaniu wszystko, co `JsonSolver` wypisze idzie na frontend, a szczegóły błędów CUDY przeciętny użytkownik chciałby uniknąć

2022-11-22 12:27 UTC, TortillaZHawaii commented on engine/src/Server/JsonSolver.cu
> +        response_builder.add_error("Internal error");
Na potrzeby inżynierki imo obejdzie się bez tego, ale implementacyjnie można jakiś middleware nałożyć który by przetwarzał output bezpośrednio z drugiego procesu.

2022-11-22 12:28 UTC, TortillaZHawaii commented
Logowanie poprawione, wynik z releasa dla odpalonych testów z `cusymint_client`:
![image](https://user-images.githubusercontent.com/62249621/203313733-a6d5258a-5d71-479a-b3df-7d89b77aa355.png)

2022-11-22 15:37 UTC, TortillaZHawaii commented
Closes #94

2022-11-22 21:40 UTC, zh-qs approved these changes

2022-11-22 21:40 UTC, merged