Liczenie pochodnych
Cusymint/cusymint pull request #110
Opened 2022-11-18 17:20 UTC by zh-qs

2022-11-19 17:12 UTC, szymon-zygula requested changes

2022-11-19 17:12 UTC, szymon-zygula commented on engine/src/Symbol/InverseTrigonometric.cu
> +        return arg().size() + 10;
Tutaj napiszę, ale odnosi się to do wszystkich implementacji `insert_reversed_derivative_at`. O ile sama idea wydaje mi się w porządku, to implementacja jest zdecydowanie do przerobienia.

Teraz wygląda właściwie tak samo, jak cusymint w kwietniu/maju, czyli ręczne ustalanie pozycji każdego symbolu w wyrażeniu i ręczne przeliczanie rozmiarów i offsetów. Bardzo szybko się to posypie. O tym, że nie jest to dobry pomysł świadczy sam fakt, że każda implementacja wymaga komentarza pokazującego, co właściwie się dzieje.

Cała implementacja tej funkcji mogłaby się ograniczyć do jednego wyrażenia (po przeniesieniu `if`a do funkcji wyżej):
```
return Prod<Frac<Integer<-1>, Sqrt<Sub<Integer<1>, Pow<Copy, Integer<2>>>>, None>::init_reverse(destination, {arg()});

```
`None` - Meta operator, który nic nie robi
`Sqrt` - `using Sqrt<T> = Pow<T, Inv<Integer<2>>>`
`init_reverse` - trzebaby zaimplementować (na ten moment wystarczyłby `init`+`reverse_iterator_sequence`), zwracałoby rozmiar utworzonego wyrażenia (można też to dodać do `init`).
Jeszcze jeśli tworzenie iloczynu też zostałoby przeniesione do funkcji wyżej, to `Prod<..., None>` byłoby niepotrzebne.

2022-11-19 17:12 UTC, szymon-zygula commented on engine/src/Symbol/InverseTrigonometric.cu
> +        }
Ten check jest robiony w każdym liczeniu pochodnej jednoargumentowych operatorów. Warto byłoby, by `insert_reversed_derivative_at` było w każdym jednoargumentowym operatorze takie samo i po prostu po sprawdzeniu tego warunku (i może też utworzeniu mnożenia, bo to też robi każdy) wołało jakąś funkcję, którą każdy operator jednoargumentowy już sobie sam implementuje.

2022-11-21 15:12 UTC, zh-qs commented on engine/src/Symbol/MetaOperators.cuh
> +        __host__ __device__ static void create_reversed_at(Symbol* const destination) {
usunąłem w ogóle ten operator

2022-11-21 15:12 UTC, zh-qs commented on engine/src/Symbol/Macros.cuh
> +         * @return Number of inserted symbols.                                     \
ok

2022-11-21 15:12 UTC, zh-qs commented on engine/src/Symbol/MetaOperators.cuh
> +    template <class T> struct ManySymbols<T> : T {};
usunąłem ten operator

2022-11-21 15:13 UTC, zh-qs commented on engine/src/Symbol/InverseTrigonometric.cu
> +        return arg().size() + 10;
ok

2022-11-21 15:13 UTC, zh-qs commented on engine/src/Symbol/InverseTrigonometric.cu
> +        }
ok

2022-11-21 15:19 UTC, zh-qs commented on engine/src/Symbol/Symbol.cuh
> +        __host__ __device__ size_t derivate_reverse_to(Symbol* const destination);
Dobra, to jednak znaczy co innego, zamienię na `derivative`

2022-11-21 18:35 UTC, szymon-zygula submitted a review, later dismissed

2022-11-22 16:57 UTC, szymon-zygula approved these changes

2022-11-22 16:57 UTC, merged