Testy kerneli i `collapse`
Cusymint/cusymint pull request #117
Opened 2022-11-22 16:27 UTC by zh-qs

Na razie zrobione do `remove_expressions`

2022-11-30 20:13 UTC, szymon-zygula requested changes

2022-11-30 20:13 UTC, szymon-zygula commented on engine/test/Evaluation/Kernels.cu
> +        }; // "40+126*x"};
A te zakomentowane?

2022-11-30 20:13 UTC, szymon-zygula commented on engine/test/Evaluation/IntegratorUtils.cu
> +    }
Nazwy tych funkcji powinny mówić, że odnoszą się do znanych całek i heurystyk

2022-12-01 10:59 UTC, zh-qs commented on engine/test/Evaluation/Kernels.cu
> +        }; // "40+126*x"};
To taka przypominajka, do odkomentowania, jak będzie rozbijanie i sumowanie wyrażeń

2022-12-01 11:04 UTC, zh-qs commented on engine/test/Evaluation/IntegratorUtils.cu
> +    }
ok

2022-12-03 10:32 UTC, szymon-zygula commented on engine/test/Evaluation/Kernels.cu
> +        }; // "40+126*x"};
Warto byłoby w takim razie dodać `// TODO: jakiś opis....`, żeby wiedzieć, o co chodziło.

2022-12-03 10:55 UTC, szymon-zygula approved these changes

2022-12-03 10:56 UTC, merged