[WIP] Dynamiczne alokacje
Cusymint/cusymint pull request #118
Opened 2022-11-22 18:04 UTC by szymon-zygula

2022-12-11 23:19 UTC, zh-qs commented on engine/src/Evaluation/Integrator.cu
> +        expressions.resize(new_expression_count, INITIAL_EXPRESSIONS_CAPACITY);
Najpierw powinien być `expressions.resize`, a potem `expressions.iterator`, bo zgłasza błąd o braniu iteratora za końcem tablicy

2022-12-12 09:41 UTC, zh-qs commented on engine/src/Evaluation/Collapser.cu
> +                help_space.resize(help_space.size() * Integrator::REALLOC_MULTIPLIER);
W ogóle można napisać jakiś helper z tą pętlą, bo w testach też jest potrzebne upraszczanie

2022-12-15 15:32 UTC, zh-qs requested changes

2022-12-15 15:32 UTC, zh-qs commented on engine/src/Symbol/ExpressionArray.cuh
> +        static constexpr size_t REALLOC_MULTIPLIER = 2;
Powtórzone z `Integrator.cuh`

2022-12-15 19:32 UTC, szymon-zygula commented on engine/src/Symbol/ExpressionArray.cuh
> +        static constexpr size_t REALLOC_MULTIPLIER = 2;
Tak, ponieważ te stałe mogłyby być w teorii różne. W `Integrator` służą do realokacji `scan_array`ów i `evaluation_status`ów, a w `ExpressionArray` do realokacji tablic wyrażeń

2022-12-15 22:18 UTC, zh-qs approved these changes

2022-12-15 22:18 UTC, merged