Rozbijanie iloczynów itp.
Cusymint/cusymint pull request #122
Opened 2022-11-25 11:00 UTC by zh-qs

Closes #102

2022-12-02 19:19 UTC, zh-qs commented on engine/src/Symbol/Macros.cuh
> +    __host__ __device__ static Util::Order compare_and_try_fuse_symbols(                      \
opisz to

2022-12-03 17:22 UTC, szymon-zygula requested changes

2022-12-03 17:22 UTC, szymon-zygula commented on engine/src/Utils/PascalTriangle.cuh
> +        __host__ __device__ static PascalTriangle generate(size_t n, size_t* data) {
const na `n`, `&` zamiast `*`, przydałaby się też jakaś dokumentacja.

2022-12-03 17:22 UTC, szymon-zygula commented on engine/src/Utils/PascalTriangle.cuh
> +        __host__ __device__ size_t binom(size_t n, size_t i) const {
Tutaj to samo

2022-12-04 14:06 UTC, zh-qs commented on engine/src/Utils/PascalTriangle.cuh
> +        __host__ __device__ size_t binom(size_t n, size_t i) const {
ok

2022-12-04 14:07 UTC, zh-qs commented on engine/src/Utils/PascalTriangle.cuh
> +        __host__ __device__ static PascalTriangle generate(size_t n, size_t* data) {
Dodałem `const`, ale nie rozumiem zmiany `*` na `&`, skoro przekazujemy jakąś wcześniej zaalokowaną tablicę wartości

2022-12-04 18:00 UTC, szymon-zygula commented on engine/src/Utils/PascalTriangle.cuh
> +        __host__ __device__ static PascalTriangle generate(size_t n, size_t* data) {
Referencje powinny być używane wszędzie gdzie się da zamiast wskaźników, bo są dużo bezpieczniejsze - nie mogą być równe `nullptr` i są domyślnie stałe

2022-12-05 16:13 UTC, szymon-zygula approved these changes

2022-12-05 22:18 UTC, merged