[WIP] Całkowanie przez części
Cusymint/cusymint pull request #129
Opened 2022-12-05 22:31 UTC by zh-qs

2022-12-22 17:33 UTC, szymon-zygula requested changes

2022-12-22 17:33 UTC, szymon-zygula commented on engine/test/Symbol/MetaOperators.cu
> +    // Init_reverse TODO
Tutaj czegoś chyba brakuje

2022-12-22 17:33 UTC, szymon-zygula commented on engine/src/Evaluation/Heuristic/IntegrateByParts.cu
> +
to może być zmienna typu `cuda::std::tuple<...>`, ewentualnie pewnie też `std::initializer_list`

2022-12-22 17:33 UTC, szymon-zygula commented on engine/src/Evaluation/Heuristic/IntegrateByParts.cu
> +    {{expression_dst.index(), 3, 0}, original_integral, first_function, *help_iterator}
to samo co do wcześniejszego `#define`

2022-12-23 12:20 UTC, zh-qs commented on engine/test/Symbol/MetaOperators.cu
> +    // Init_reverse TODO
Zrobione

2022-12-23 12:20 UTC, zh-qs commented on engine/src/Evaluation/Heuristic/IntegrateByParts.cu
> +
ok

2022-12-23 12:20 UTC, zh-qs commented on engine/src/Evaluation/Heuristic/IntegrateByParts.cu
> +    {{expression_dst.index(), 3, 0}, original_integral, first_function, *help_iterator}
ok

2022-12-23 13:02 UTC, szymon-zygula approved these changes

2022-12-23 13:02 UTC, merged