[WIP] Nierekurencyjny `is_function_of`
Cusymint/cusymint pull request #134
Opened 2022-12-07 09:14 UTC by zh-qs

2022-12-22 17:49 UTC, szymon-zygula requested changes

2022-12-22 17:49 UTC, szymon-zygula commented on engine/src/Evaluation/Integrator.cu
> +                   INITIAL_ARRAYS_EXPRESSIONS_CAPACITY), // heuristic count???
tak, możnaby tu uwzględnić liczbę heurystyk/znanych całek (jest już w `Integrator`ze stała `MAX_CHECK_COUNT`, czy coś takiego).

2022-12-22 17:49 UTC, szymon-zygula commented on engine/src/Symbol/ExpressionArray.cuh
> +                           const size_t multiplier = 1) { // TODO: change to repeat_reoffset_like(other, 1, multiplier)
trzebaby zmienić

2022-12-22 17:49 UTC, szymon-zygula commented on engine/src/Symbol/ExpressionArray.cuh
> +
Ta funkcja sprowadza się do `reoffset_like` gdy `count == 1`, można więc je połączyć w jedną i ustawić domyślną wartość dla `count`

2022-12-23 12:56 UTC, zh-qs commented on engine/src/Symbol/ExpressionArray.cuh
> +                           const size_t multiplier = 1) { // TODO: change to repeat_reoffset_like(other, 1, multiplier)
już się robi

2022-12-23 12:57 UTC, zh-qs commented on engine/src/Symbol/ExpressionArray.cuh
> +
ok

2022-12-28 18:14 UTC, szymon-zygula approved these changes

2022-12-28 18:14 UTC, merged