Historia obliczeń
Cusymint/cusymint pull request #137
Opened 2022-12-08 15:55 UTC by zh-qs

W kernelu `ExpressionArray::reoffset_data` wyskakiwał błąd `cudaErrorLaunchOutOfResources`, więc zmniejszyłem liczbę wątków na blok

2023-01-04 17:24 UTC, szymon-zygula requested changes
Uwagi do całości:
1. Przy podstawieniach mamy zawsze "Substitute u = f(x0, du=g(x)*1dx" (to *1 jest niepotrzebne)
2. Przy podzieleniu całki na sumę całek trochę się miesza output, np. dla  całki z `e^x*e^e^x+20sin(x)` dostajemy po uproszczeniu coś takiego (jedna linijka bezpośrednio po drugiej):
```
Substitute: u=e^x, du=e^x ln(e)*1dx:
Substitute: u=cos(x), du=-sin(x)*1dx:
```
3. Całka z `5x` ma błąd w historii, w pewnym momencie jest
```
Solve integral: int x du_? = 0.5x^2 + C
```
(chodzi o `du_?`)

2023-01-04 17:24 UTC, szymon-zygula commented on engine/src/Symbol/SubexpressionCandidate.cu
> +                           uid, creator_uid, vacancy_expression_idx, vacancy_idx, subexpressions_left, arg().to_string());
Ten string jest już na tyle długi, że możnaby dodać podobne `xxx={}` dla pozostałych placeholderów

2023-01-04 17:24 UTC, szymon-zygula commented on engine/src/main.cu
> +    history.print_history();
To niepotrzebne w zwykłym niedebugowym kodzie, jest już potem wypisanie historii texu.

2023-01-05 10:00 UTC, zh-qs commented on engine/src/main.cu
> +    history.print_history();
ok

2023-01-05 11:43 UTC, zh-qs commented
1. Dodałem jedno wywołanie simplify() po policzeniu pochodnej, powinno wystarczyć dla prostych funkcji (których używamy w podstawieniach albo całkach przez części)
2. To normalne zachowanie, ponieważ oba podstawienia zostały wykonane jednocześnie
3. Poprawiłem

2023-01-07 14:37 UTC, szymon-zygula approved these changes

2023-01-07 21:35 UTC, merged