[WIP] Integral expressions
Cusymint/cusymint pull request #14
Opened 2022-09-29 17:28 UTC by szymon-zygula

Długo wyczekiwany update, wyrażenia złożone z całek, główna pętla obliczeń, sporo innych poprawek.

2022-10-09 20:38 UTC, TortillaZHawaii commented
Resolves #17, resolves #18 and resolves #31

2022-10-12 09:39 UTC, zh-qs commented on engine/src/Symbol/SubexpressionCandidate.cuh
> +
brakuje #include <vector>

2022-10-12 09:39 UTC, zh-qs commented on engine/src/Symbol/SubexpressionVacancy.cu
> +
brakuje `#include <vector>`

2022-10-12 09:40 UTC, zh-qs commented on engine/src/Symbol/SubexpressionVacancy.cuh
> +
brakuje `#include <vector>`

2022-10-14 07:53 UTC, TortillaZHawaii commented on engine/src/Utils/Cuda.cuh
> +        printf("\n");
Nie lepiej wyrzucać tego na `stderr`?

2022-10-14 08:24 UTC, TortillaZHawaii commented on engine/src/main.cu
> +solve_integral(const std::vector<Sym::Symbol>& integral) {
Imo warto przenieść do osobnego pliku, żeby przy testowaniu dało się includować funkcję `solve_integral`.

2022-10-15 09:27 UTC, szymon-zygula commented on engine/src/Utils/Cuda.cuh
> +        printf("\n");
W trakcie wywołania kerneli stderr jest niedostępne (fprintf nie działa)

2022-10-15 09:34 UTC, szymon-zygula commented on engine/src/main.cu
> +solve_integral(const std::vector<Sym::Symbol>& integral) {
Przeniesione do `Integrate.cu`

2022-10-15 18:37 UTC, zh-qs requested changes

2022-10-15 18:37 UTC, zh-qs commented on engine/src/Evaluation/Integrate.cu
> +        for (size_t i = 0;; ++i) {
Kod pętli nie jest dość czytelny według mnie, wydaje mi się, że można by go podzielić na pojedyncze etapy, o których mówiłeś na MiNI, i te etapy poprzerzucać do osobnych funkcji

2022-10-15 19:07 UTC, zh-qs commented on engine/src/Symbol/SymbolType.cuh
> +            break;
`break` nie jest potrzebny po instrukcji `return`

2022-10-15 19:16 UTC, zh-qs commented on engine/src/Symbol/SymbolType.cuh
> +        // I could not find a better way to this that would work on both CPU and GPU
Myślę, że można się zastanowić nad jakimś prostym generatorem pliku `SymbolType.cuh` w miarę przybywających symboli; proponuję jeszcze przenieść tu makro `VIRTUAL_CALL`, bo wtedy sprawy ze wszystkimi switchami załatwiałoby się w jednym pliku

2022-10-18 16:06 UTC, szymon-zygula commented on engine/src/Symbol/SymbolType.cuh
> +        // I could not find a better way to this that would work on both CPU and GPU
VIRTUAL_CALL lepiej żeby został w Symbol.cu, bo jest to taka pseudo metoda na Symbol i tylko tam jest używane. Co do generowania pliku, to mogłaby być to dobra opcja, ale raczej na inny PR.

2022-10-18 18:51 UTC, szymon-zygula commented on engine/src/Evaluation/Integrate.cu
> +        for (size_t i = 0;; ++i) {
Ogólnie to w Integrate.cu trzeba potem zrobić większy porządek, rozbić go na więcej plików. Teraz jest tam za dużo rzeczy, które nie są ściśle powiązane. Wtedy można też zająć się rozbiciem tej funkcji.

2022-10-18 21:57 UTC, zh-qs commented on engine/src/Evaluation/Integrate.cu
> +        for (size_t i = 0;; ++i) {
dodam to jako issue w takim razie

2022-10-18 21:57 UTC, zh-qs commented on engine/src/Symbol/SymbolType.cuh
> +        // I could not find a better way to this that would work on both CPU and GPU
też dodam jakieś opcjonalne issue

2022-10-18 22:00 UTC, zh-qs approved these changes

2022-10-18 22:00 UTC, merged