[WIP] `Sign` symbol, integral of `1/x`
Cusymint/cusymint pull request #147
Opened 2022-12-17 14:09 UTC by szymon-zygula

2022-12-18 16:15 UTC, szymon-zygula commented
@zh-qs prośba o dodanie `|f|` i `sgn(f)` do parsera

2022-12-21 22:44 UTC, zh-qs commented
Zamiast `|f|` dodam `abs(f)`, symbol `|` wprowadza niejednoznaczność, np. `|a|b|c|` nie wiadomo, czy jest `abs(a*abs(b)*c)`, czy `abs(a)*b*abs(c)`

2022-12-30 19:16 UTC, szymon-zygula commented
Czekam na merge https://github.com/Cusymint/cusymint/pull/159 by kontynuować prace

2023-01-03 19:43 UTC, szymon-zygula commented
Gotowe do review

2023-01-04 11:08 UTC, zh-qs requested changes

2023-01-04 11:08 UTC, zh-qs commented on engine/test/Simplify.cu
> +    EQUALITY_TEST(AbsoluteValueOfNegation, "abs(-x)", "abs(x)")
Przydałby się jeszcze test z upraszczaniem mnożenia wewnątrz `sgn`, bo ten długi kawałek kodu w `Sign::simplify_in_place` nie jest na razie sprawdzany

2023-01-04 16:37 UTC, szymon-zygula commented on engine/src/Symbol/Sign.cu
> +    DEFINE_INSERT_REVERSED_DERIVATIVE_AT(Sign) {
Niestety nie można, bo makro to wymaga, by pochodna była meta operatorem który ma w szablonie `Copy`, a tutaj tego nie ma.

2023-01-05 08:22 UTC, zh-qs commented on engine/src/Symbol/Sign.cu
> +    DEFINE_INSERT_REVERSED_DERIVATIVE_AT(Sign) {
Faktycznie

2023-01-05 08:28 UTC, zh-qs commented on engine/src/Symbol/Sign.cu
> +    DEFINE_INSERT_REVERSED_DERIVATIVE_AT(Sign) {
W takim razie trzeba podejrzeć w poprzednim symbolu, ile miejsca zajmuje (czyli do pochodnej argumentu `sgn`), cofnąć się do jego początku, wstawić tam `0` i zwrócić `1 - rozmiar`. Funkcja licząca pochodną zakłada, że to, co wyliczone wcześniej, jest spójne, a wpisanie `0` w `dst` i zwrócenie `1` zostawi pochodną argumentu, czyli śmieci

2023-01-05 08:53 UTC, zh-qs requested changes

2023-01-05 08:53 UTC, zh-qs commented on engine/src/Symbol/Sign.cu
> +    DEFINE_DERIVATIVE_SIZE(Sign) { return 1; }
Tu to samo co wyżej

2023-01-05 08:53 UTC, zh-qs commented on engine/src/Symbol/Sign.cu
> +                        help_space[variable_expressions_size].init_from(Variable::create());
Nie rozumiem tego, nie powinno być tu `power.arg1().copy_to(help_space[...])`?

2023-01-08 19:54 UTC, zh-qs approved these changes

2023-01-08 19:54 UTC, merged