Optimize simplify
Cusymint/cusymint pull request #149
Opened 2022-12-18 16:11 UTC by szymon-zygula

Adds shared memory cache to `simplify` kernel.

2022-12-20 16:00 UTC, zh-qs requested changes

2022-12-20 16:55 UTC, szymon-zygula commented on engine/src/Evaluation/IntegratorKernels.cu
> -            }
Zorientowałem się, że wszystkie `for`y w tych kernelach są niepotrzebne. W Cudzie można uruchamiać kernele z 2^32-1 blokami, więc zawsze można ich zrobić wystarczająco dużo, by nie była potrzebna pętla (zmienił się też sposób wywoływania `simplify` na właśnie taki).

2022-12-20 16:58 UTC, szymon-zygula commented on engine/src/Evaluation/IntegratorKernels.cu
> +            expressions[expr_idx].copy_to(expr_cache);
To sprawdzenie jest w kernelu `simplify` jako część `use_cache` (`expressions[expr_idx].size() * (1 + Integrator::HELP_SPACE_MULTIPLIER) <= cache_symbols_per_thread`, czyli na wątek jest odpowiednio dużo pamięci dla wyrażenia i help space). Niezbyt widzę potrzebę sprawdzania tego drugi raz w debugu.

2022-12-21 22:14 UTC, zh-qs commented on engine/src/Evaluation/IntegratorKernels.cu
> -            }
W takim razie myślę, że dobrze by było dla spójności powywalać `for`y ze wszystkich kerneli

2022-12-21 22:15 UTC, zh-qs commented on engine/src/Evaluation/IntegratorKernels.cu
> +            expressions[expr_idx].copy_to(expr_cache);
Okej, rozumiem

2022-12-22 11:27 UTC, zh-qs requested changes
dodałem komentarz odnośnie `for`ów

2022-12-22 17:49 UTC, szymon-zygula commented on engine/src/Evaluation/IntegratorKernels.cu
> -            }
Tak, ale myślę, że to już robota na inny PR

2022-12-23 12:01 UTC, zh-qs commented on engine/src/Evaluation/IntegratorKernels.cu
> -            }
ok

2022-12-23 12:01 UTC, zh-qs approved these changes

2022-12-23 12:01 UTC, merged