Feature/is function of overhaul
Cusymint/cusymint pull request #42
Opened 2022-10-22 21:29 UTC by szymon-zygula

Najpierw należy zrobić merge `feature/refactor-heuristics`

2022-10-24 16:07 UTC, zh-qs requested changes

2022-10-24 16:07 UTC, zh-qs commented on engine/src/Symbol/InverseTrigonometric.cu
>      DEFINE_SIMPLIFY_IN_PLACE(Arcsine) { arg().simplify_in_place(help_space); }
dla kompletu można dopisać uproszczenie `arctrig(trig(x))=x`

2022-10-24 16:07 UTC, zh-qs commented on engine/src/Symbol/Trigonometric.cu
> +            help_space->copy_to(symbol());
Nie można od razu skopiować do `symbol()`? Nasza funkcja kopiująca bierze przecież kolejno elementy tablicy i wstawia je w nowe miejsce; kopiowanie "w tył" tablicy nie zniszczy żadnych danych 
(jakby co, to zrobiłem tak w jednym miejscu XD)

2022-10-24 19:35 UTC, szymon-zygula commented on engine/src/Symbol/Trigonometric.cu
> +            help_space->copy_to(symbol());
Teoretycznie tak, ale jakby ktoś z jakiegoś powodu coś tam zmienił i by to nie było już prawdą, to powstałby cieżki do znalezienia bug, dlatego lepiej nie polegać na takich szczegółach implementacyjnych.

2022-10-25 00:07 UTC, zh-qs commented on engine/src/Symbol/InverseTrigonometric.cu
>      DEFINE_SIMPLIFY_IN_PLACE(Arcsine) { arg().simplify_in_place(help_space); }
no tak, faktycznie; trzeba by tu całkować kawałkami; do pomyślenia, ale na pewno nie w tym PR-ze

2022-10-25 00:11 UTC, zh-qs submitted a review, later dismissed

2022-10-25 18:38 UTC, merged