Add logarithms and square root
Cusymint/cusymint pull request #43
Opened 2022-10-23 19:29 UTC by zh-qs

Dodałem symbol Logarithm (reprezentuje ln), jakieś uproszczenia na nim oraz do parsera uzupełniłem rozpoznawanie ln, logarytmu o dowolnej podstawie i pierwiastka kwadratowego, ponadto dodałem do funkcji Power::to_tex() i Product::to_tex() instrukcje, żeby zwracało zapis pierwiastka i nie tylko logarytmu naturalnego (wyłącznie względy estetyczne XD)

2022-10-23 20:36 UTC, szymon-zygula requested changes

2022-10-23 20:36 UTC, szymon-zygula commented on engine/src/Symbol/Logarithm.cu
> +            this->as<Product>()->second_arg_offset = 1 + arg().logarithm.size;
To można nieco ładniej i bezpieczniej zrobić tak:
```
            arg().power.type = Type::Logarithm;
            arg().as<Logarithm>().seal();
            this->type = Type::Product;
            this->as<Product>().seal();
```
Notacji `(...).[power|logarithm|...]` raczej powinniśmy unikać i używać `Symbol::as<XXX>`, bo w trybie debug sprawdza, czy rzutowanie ma sens. Natomiast o `XXX::as<YYY>` w ogóle zapomniałem, że istnieje, i tak naprawdę to jest do usunięcia, bo niepotrzebnie duplikuje tę funkcję z `Symbol`.

2022-10-23 20:36 UTC, szymon-zygula commented on engine/src/Symbol/Logarithm.cuh
> +    DECLARE_SYMBOL(Logarithm, false)
Tutaj jest bardzo ważne pytanie, czy chcemy rzeczywiście wszystkie logarytmy jako `ln(a)/ln(b)`. Nie jestem pewien, czy nas to gdzieś znienacka potem nie ugryzie. Tylko taka myśl.

2022-10-23 20:36 UTC, szymon-zygula commented on engine/src/Symbol/Logarithm.cu
> +    DEFINE_SIMPLIFY_IN_PLACE(Logarithm) {
W `Power` można też od razu dodać uproszczenie `a^(... * 1/ln(a) * ...)` -> `e^(...)` oraz `e^(... * ln(b) * ...)` -> `b^(...)`.

Jak się użyje `TreeIterator` (przykład użycia w `simplify_pairs` w upraszczaniu w `Product`), to nie powinno być trudne. Można zrobić coś takiego, by się nie narobić: `a^(... * 1/ln(a) * ...)` -> `e^(... * 1 * ...)`.

Potem na koniec jeszcze raz `simplify` na całym `Power` (ale jako `symbol()->simplify_in_place()`, żeby wykonało się też `compress_reverse_to`), by zgarnąć ew. kolejne wystąpienia tego typu i by się usunęła ta dodana jedynka, lub by inne uproszczenia które stały się, możliwe były wykonane (np w przypadku `e^(4*ln(2))` będzie `e^(4*ln(2))`->`2^(4*1)`->`2^4`->`16`).

2022-10-24 09:18 UTC, zh-qs commented on engine/src/Symbol/Logarithm.cu
> +            this->as<Product>()->second_arg_offset = 1 + arg().logarithm.size;
cenna uwaga

2022-10-24 09:21 UTC, zh-qs commented on engine/src/Symbol/Logarithm.cu
> +    DEFINE_SIMPLIFY_IN_PLACE(Logarithm) {
Jeszcze trzeba pogadać o potencjalnym uproszczeniu logarytmu iloczynu na sumę logarytmów, nie robiłem na razie tego, bo te uproszczenie zwiększa długość wyrażenia (o tym porozmawiamy XD) i zastanawiam się, czy zawsze jest to przydatne

2022-10-24 09:26 UTC, zh-qs commented on engine/src/Parser/Parser.cu
>      const SymbolicFunction empty = [](const std::vector<Sym::Symbol>& symbol) { return symbol; };
ok

2022-10-24 09:27 UTC, zh-qs commented on engine/src/Symbol/Product.cu
> +            //                   arg2().reciprocal.arg().to_tex());
ok

2022-10-24 20:22 UTC, szymon-zygula requested changes

2022-10-24 20:22 UTC, szymon-zygula commented on engine/src/Symbol/Logarithm.cu
> +#include "InverseTrigonometric.cuh"
Znalazłem jakiś błąd. Całka z
`e^(ln(2)*ln(x))+2^(x/ln(2))*e^e^x` liczy się ok, ale
`e^(ln(x)*ln(2))+2^(x/ln(2))*e^e^x` nie znajduje rozwiązania (różnica w kolejności argumentów mnożenia w wykładniku), a
`e^(ln(x)*ln(2))` zawiesza program (pewnie gdzieś wchodzi w nieskończoną pętlę).

2022-10-24 20:37 UTC, zh-qs commented on engine/src/Symbol/Logarithm.cu
> +            symbol();
nie umiem się wytłumaczyć z tego symbola() XD

2022-10-24 22:07 UTC, szymon-zygula approved these changes

2022-10-24 22:10 UTC, merged