Non-recursive `simplify()` and `compress_reverse_to()`, expression extending
Cusymint/cusymint pull request #52
Opened 2022-10-30 09:18 UTC by zh-qs

2022-10-31 09:14 UTC, zh-qs commented on engine/src/Symbol/Symbol.cu
> +#include <sys/types.h>
czemu to tu jest XD

2022-11-03 22:20 UTC, szymon-zygula requested changes

2022-11-03 22:20 UTC, szymon-zygula commented on engine/src/Symbol/Symbol.cuh
>           */
To jest dalej aktualne? Widziałem, że niektóre symbole zawsze zwracają 1

2022-11-03 22:20 UTC, szymon-zygula commented on engine/src/Symbol/Macros.cuh
> +
To makro jest niepotrzebne, wygląda jak antipattern. Można pomyśleć natomiast nad krótszą nazwą dla `put_children_on_stack_and_propagate_additional_size`, np po prostu `propagate_additional_size`.

2022-11-03 22:20 UTC, szymon-zygula commented on engine/src/Symbol/Addition.cu
> +            return false; // created addition needs to be simplified again, but without additional size
Coś podobnego dobrze byłoby też zaimplementować dla `Reciprocal` z argumentem `Product`

2022-11-04 16:30 UTC, zh-qs commented on engine/src/Utils/StaticStack.cuh
> +        size_t current_idx;
ok

2022-11-04 16:32 UTC, zh-qs commented on engine/src/Utils/StaticStack.cuh
> +            __host__ __device__ explicit StaticStack(void* table): table(reinterpret_cast<T*>(table)), current_idx(0) { }
wtedy myślę, że nie do końca wiadomo by było o co chodzi, a konstruktorowi trzeba podać po prostu jakiś wskaźnik do zaalokowanej pamięci

2022-11-04 16:33 UTC, zh-qs commented on engine/src/Utils/StaticStack.cuh
> +        T* table;
ok

2022-11-04 16:35 UTC, zh-qs commented on engine/src/Utils/StaticStack.cuh
> +            __host__ __device__ explicit StaticStack(void* table): table(reinterpret_cast<T*>(table)), current_idx(0) { }
dodałem komentarz do konstruktora

2022-11-04 16:35 UTC, zh-qs commented on engine/src/Symbol/Symbol.cu
> +    __host__ __device__ size_t Symbol::compress_reverse_to(Symbol* const destination) /*const*/ {
bo zapomniałem usunąć komentarz

2022-11-04 16:36 UTC, zh-qs commented on engine/src/Symbol/Symbol.cu
> +        } while (!success);
faktycznie, poprawiam

2022-11-04 16:39 UTC, zh-qs commented on engine/src/Utils/StaticStack.cuh
> +            }
ok

2022-11-04 16:41 UTC, zh-qs commented on engine/src/Symbol/MetaOperators.cuh
> +                iterator.current()->copy_to(terms + 1);
ok

2022-11-04 16:46 UTC, zh-qs commented on engine/src/Symbol/Macros.cuh
> +
z makrem się zgadzam, ale ta funkcja oryginalnie miała właśnie dokładać dzieci na stos, propagacja dodatkowego rozmiaru jest jakby przy okazji, myślę, że skrócenie tej nazwy ukryłoby część rzeczy, która się tam dzieje

2022-11-04 16:48 UTC, zh-qs commented on engine/src/Symbol/Macros.cuh
> +
usunąłem makro

2022-11-04 16:50 UTC, zh-qs commented on engine/src/Symbol/Addition.cu
> +            return false; // created addition needs to be simplified again, but without additional size
tak, także dla logarytmów z iloczynem i potęg z dodawaniem, ale myślę, że to robota na następny PR, to napisałem bardziej dla sprawdzenia, czy reszta działa

2022-11-05 15:20 UTC, szymon-zygula commented on engine/src/Utils/StaticStack.cuh
> +            __host__ __device__ explicit StaticStack(void* table): table(reinterpret_cast<T*>(table)), current_idx(0) { }
Nie do końca. `void*` może mieć dowolny alignment (np. może być adresem 0x1), a StaticStack przetrzymuje tablicę symboli, która musi mieć taki sam alignment jak Symbol (w tym momencie pewnie wynosi 8, czyli `table` musi być wielokrotnością 8). Więc zarówno z punktu widzenia czytelności jak i poprawności nie powinniśmy używać `void*`.

2022-11-05 19:40 UTC, zh-qs commented on engine/src/Utils/StaticStack.cuh
> +            __host__ __device__ explicit StaticStack(void* table): table(reinterpret_cast<T*>(table)), current_idx(0) { }
W kodzie `StaticStack` trzyma nie tablicę symboli, tylko tablicę wskaźników do symboli, to była moja główna motywacja do dania tam `void*`, bo muszę i tak użyć `reinterpret_casta`

2022-11-05 19:41 UTC, zh-qs commented on engine/src/Symbol/MetaOperators.cuh
> +    template <class OneArgOp, class TwoArgOp> struct LargeOperatorWithFunction {
ok

2022-11-05 19:43 UTC, zh-qs commented on engine/src/Symbol/MetaOperators.cuh
> +        __host__ __device__ static void init_from_tree(Symbol& dst, SymbolTree& tree, size_t count) {
Zmieniłem nieco podejście, zamiast długiej, mało znaczącej nazwy `LargeOperatorWithFunction`, zrobiłem coś w rodzaju `From<Tree>::Create<AnotherTree>::WithMap<OneArgOp>`. Z tego będzie ładniejsze wyjście do tworzenia `AnotherTree` ze składnikami niezmienionymi żadną funkcją.

2022-11-06 20:21 UTC, szymon-zygula approved these changes

2022-11-06 20:21 UTC, merged