Server
Cusymint/cusymint pull request #71
Opened 2022-11-07 19:44 UTC by TortillaZHawaii

Jest to sama implementacja serwera, można sprawdzić za pomocą narzędzia `wscat`:
![image](https://user-images.githubusercontent.com/62249621/200398634-defd3462-de04-4146-b9e3-56a567f3aa69.png)

Ostatecznie nie udało mi się dołączyć `mongoose.h` do Cmake przez `fetch`.
Bardzo nie orientuje się jak zbierać rozwiązania z `Sym::solve_integral`, ale chyba jest ok?
Tak samo jest z obsługą błędów zarówno z `Sym::solve_integral` jak i z parsera.

Client będzie w oddzielnym PR.

2022-11-07 20:37 UTC, szymon-zygula commented
Pewnie jutro zrobię review. Poza tym na pewno spróbuję dodać mongoose przez CMake, bo bardzo nie podoba mi się bezpośrednio wsadzanie jego plików tutaj.

2022-11-08 14:31 UTC, zh-qs commented on engine/src/Server/JsonFormatter.cu
> +        json += input->to_string();
Brakuje cudzysłowów dookoła zwracanych wartości, tj. zwraca `"inputInUtf":x+1` zamiast `"inputInUtf":"x+1"`

2022-11-08 14:34 UTC, zh-qs commented on engine/src/Server/JsonFormatter.cu
> +#include "JsonFormatter.cuh"
Czytelniej chyba będzie, jak użyjesz `fmt`

2022-11-08 22:19 UTC, szymon-zygula requested changes

2022-11-08 22:19 UTC, szymon-zygula commented on engine/CMakeLists.txt
> +target_link_libraries(libcusymint PUBLIC fmt::fmt libmongoose)
mongoose powinno być linkowane do `srvcusymint`, nie `libcusymint`

2022-11-09 12:22 UTC, zh-qs commented on engine/CMakeLists.txt
> +target_link_libraries(libcusymint PUBLIC fmt::fmt libmongoose)
To trzeba jeszcze przepisać pliki źródłowe z libcusymint do srvcusymint

2022-11-09 13:34 UTC, zh-qs commented on engine/CMakeLists.txt
> +target_link_libraries(libcusymint PUBLIC fmt::fmt libmongoose)
zrobione

2022-11-09 13:36 UTC, zh-qs commented
> Naniosłem poprawki do `JsonFormatter`. Próbowałem dodać testy, ale mam problem z `nvcc fatal : Unknown option '-Wall'` przy kompilacji `testcusymint`.

Zobacz może, czy kompilujesz z flagą `-forward-unknown-to-host-compiler`

2022-11-09 19:34 UTC, szymon-zygula approved these changes

2022-11-09 19:34 UTC, merged