Całkowite usunięcie rekurencji z `simplify()`
Cusymint/cusymint pull request #72
Opened 2022-11-08 10:25 UTC by zh-qs

Okazało się, że nvlink krzyczy także na rekurencje ogonkowe, zamieniłem ogonkowe wersje na nierekurencyjne odpowiedniki (w `simplify_pairs` zrobiłem to dość prymitywnie, może być miejsce na optymalizację)

2022-11-08 22:05 UTC, szymon-zygula requested changes

2022-11-08 22:05 UTC, szymon-zygula commented on engine/src/Symbol/Macros.cuh
> +        return last_in_tree()->symbol() - symbol() + 2;                                                    \
Tu przydałby się komentarz, dlaczego to działa.

2022-11-08 22:05 UTC, szymon-zygula commented on engine/src/Symbol/Power.cu
> +                arg2().as_ptr<Product>()->eliminate_ones();
`as_ptr` chyba niepotrzebny, wystarczy `as`

2022-11-09 14:02 UTC, zh-qs commented on engine/src/Symbol/Macros.cuh
> +                         * Dzięki rekurencji ogonkowej call stack nie będzie rosnąć.                   \
usunąłem linijkę o rekurencji

2022-11-09 14:03 UTC, zh-qs commented on engine/src/Symbol/Macros.cuh
> +        return last_in_tree()->symbol() - symbol() + 2;                                                    \
dodałem

2022-11-09 14:03 UTC, zh-qs commented on engine/src/Symbol/Power.cu
> +                arg2().as_ptr<Product>()->eliminate_ones();
ok

2022-11-09 19:13 UTC, szymon-zygula approved these changes

2022-11-09 19:13 UTC, merged