Testy parsera + poprawki
Cusymint/cusymint pull request #78
Opened 2022-11-10 10:58 UTC by zh-qs

Mam nadzieję, że wystarczająca liczba 140 testów sprawdzających czytanie tokenów oraz podstawowe własności w wyrażeniach arytmetycznych, które parser powinien rozpoznawać.
Poza tym wprowadziłem kilka poprawek:
- sprawdzanie równości `UnknownConstant` przez nową funkcję `compare_str` (naśladującą `strncmp`),
- zamiana `stof` na `stod` w parsowaniu liczby zmiennoprzecinkowej,
- sprawdzanie, czy po przeczytaniu nazwy funkcji (np. `sin`), nie ma za tym jeszcze jakichś liter (np. `sinxxx`) (oczywiście `sinh` jest nadal dopuszczalne)
- czytanie wyrażeń typu `int e^x dx`, `integral x`, `integrate x^2` itp. (parser za to nie owija wyrażenia w symbol całki, bo i tak po przeczytaniu wyrażenia np. `x^3+1`, później zostanie owinięte).

2022-11-10 19:16 UTC, szymon-zygula requested changes

2022-11-10 19:16 UTC, szymon-zygula commented on engine/src/Symbol/Constants.cuh
> +#include <fmt/core.h>
Niepotrzebny include.
Btw, używajmy tych konwencji co do kolejności includów (+ ewentualnie entery między includami z różnych modułów u nas, np. includami z `Evaluate` i `Symbol`):
https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes

2022-11-10 19:16 UTC, szymon-zygula commented on engine/src/Utils/Cuda.cuh
> +                                         const size_t n);
`n` może mieć domyślną wartość `std::numeric_limits<size_t>::max()`

2022-11-10 19:16 UTC, szymon-zygula commented on engine/test/Parser/Parser.cu
> +PARSER_TEST(SymbolicConstant, "a", Sym::cnst("a"))
Parser wspiera stałe o większej długości? Jeśli tak, to przydałby się test z taką stałą.

2022-11-10 19:21 UTC, szymon-zygula requested changes

2022-11-10 19:21 UTC, szymon-zygula commented on engine/test/Parser/Parser.cu
> +
Tutaj wszystko dodałbym do namespace Test, tak jak w `test/KnownIntegral.cu`. `test_parse` i `test_parser_error` bym jeszcze dodatkowo dał w anonymous namespace. Ta sama uwaga do pliku Scanner.cu

2022-11-10 19:26 UTC, szymon-zygula requested changes

2022-11-10 19:26 UTC, szymon-zygula commented on engine/src/Parser/Parser.cuh
> +// parser does not wrap expression in `Sym::Integral` symbol.
To chyba nie jest tym, czego byśmy chcieli. Na pewno decyzja o tym nie powinna być podejmowana na poziomie parsera tylko gdzieś wyżej, inaczej odcinamy się całkowicie od możliwości parsowania wyrażeń, które chcemy owinąć w całkę.

2022-11-10 19:27 UTC, szymon-zygula requested changes

2022-11-10 19:27 UTC, szymon-zygula commented on engine/src/Parser/Parser.cuh
>  using SymbolicOperator = std::vector<Sym::Symbol> (*)(const std::vector<Sym::Symbol>&,
Jak już są robione teraz poprawki w parserze, to proponowałbym dodać namespace Parser

2022-11-11 17:54 UTC, TortillaZHawaii commented on engine/src/Parser/Parser.cuh
> +// parser does not wrap expression in `Sym::Integral` symbol.
+1000

2022-11-12 07:57 UTC, zh-qs commented on engine/test/Parser/Parser.cu
> +PARSER_TEST(SymbolicConstant, "a", Sym::cnst("a"))
Wspiera tylko jednoliterowe stałe, nieznane dwuliterowe ciągi i dłuższe są odrzucane

2022-11-12 08:02 UTC, zh-qs commented on engine/src/Symbol/Constants.cuh
> +#include <fmt/core.h>
ok

2022-11-12 08:02 UTC, zh-qs commented on engine/src/Utils/Cuda.cuh
> +                                         const size_t n);
ok

2022-11-12 08:03 UTC, zh-qs commented on engine/test/Parser/Parser.cu
> +
ok

2022-11-12 08:04 UTC, zh-qs commented on engine/src/Parser/Parser.cuh
> +// parser does not wrap expression in `Sym::Integral` symbol.
Rozumiem, w takim razie owijanie w całkę dopiszę do solvera

2022-11-12 08:42 UTC, zh-qs commented on engine/src/Parser/Parser.cuh
>  using SymbolicOperator = std::vector<Sym::Symbol> (*)(const std::vector<Sym::Symbol>&,
ok

2022-11-12 09:53 UTC, szymon-zygula approved these changes

2022-11-12 09:53 UTC, merged