Feature/rational functions simplifying
Cusymint/cusymint pull request #81
Opened 2022-11-10 15:07 UTC by zh-qs

Dzielenie wielomianów

2022-11-16 20:14 UTC, szymon-zygula requested changes

2022-11-16 20:14 UTC, szymon-zygula commented on engine/src/Symbol/Product.cu
> +        Addition* plus = symbol() << Addition::builder();
`Addition* const`

2022-11-16 20:14 UTC, szymon-zygula commented on engine/src/Symbol/Product.cu
> +        Product* prod = &plus->arg2() << Product::builder();
`Product* const`

2022-11-16 20:14 UTC, szymon-zygula commented on engine/src/Symbol/Product.cu
> +        Reciprocal* rec = &prod->arg2() << Reciprocal::builder();
`Reciprocal* const`

2022-11-16 20:14 UTC, szymon-zygula commented on engine/src/Symbol/Polynomial.cu
> +    }
Jeśli `Polynomial` to tylko symbol pomocniczy który nie powinien istnieć poza `simplify`, to lepsze byłoby tutaj `DEFINE_INVALID_IS_FUNCTION_OF`.

2022-11-16 20:14 UTC, szymon-zygula commented on engine/src/Symbol/Polynomial.cu
> +                                                            Symbol* const destination) {
Może `make/init_polynomial_at`? `make to` jest trochę niegramatyczne.

2022-11-16 20:14 UTC, szymon-zygula commented on engine/src/Symbol/Polynomial.cu
> +        auto* dst_coefs = term_coefficients + symbol->size();
`auto* const` do wszystkich wskaźników

2022-11-16 20:14 UTC, szymon-zygula commented on engine/src/Symbol/Polynomial.cu
> +        case Type::Variable:
warto dodać `[[fallthrough]]`

2022-11-16 20:14 UTC, szymon-zygula commented on engine/src/Symbol/Polynomial.cu
> +        double* coefs = dest_poly.coefficients();
double* const

2022-11-17 09:51 UTC, zh-qs commented on engine/src/Symbol/Polynomial.cu
> +    std::string Polynomial::to_string() const { // TODO lepiej!
XDDDDDD

2022-11-17 10:00 UTC, zh-qs commented on engine/src/Symbol/Polynomial.cu
> +        double* coefs = dest_poly.coefficients();
ok

2022-11-17 10:01 UTC, zh-qs commented on engine/src/Symbol/Polynomial.cu
> +        auto* dst_coefs = term_coefficients + symbol->size();
ok

2022-11-17 10:01 UTC, zh-qs commented on engine/src/Symbol/Polynomial.cu
> +            // printf("\n");
ok

2022-11-17 10:01 UTC, zh-qs commented on engine/src/Symbol/Polynomial.cu
> +        // printf("\n");
ok

2022-11-17 10:05 UTC, zh-qs commented on engine/src/Symbol/Polynomial.cu
> +        case Type::Variable:
ok

2022-11-17 10:14 UTC, zh-qs commented on engine/src/Symbol/Addition.cu
> +        ssize_t const rank2 = ranks[&arg2() - symbol()];
ok

2022-11-17 10:16 UTC, zh-qs commented on engine/src/Utils/Cuda.cuh
> +
ok

2022-11-17 10:21 UTC, zh-qs commented on engine/src/Symbol/Product.cu
> +        if (!arg2().is(Type::Reciprocal) && arg1().is(Type::Reciprocal)) {
ok

2022-11-17 10:24 UTC, zh-qs commented on engine/src/Symbol/Product.cu
> +        Addition* plus = symbol() << Addition::builder();
ok

2022-11-17 10:24 UTC, zh-qs commented on engine/src/Symbol/Product.cu
> +        Product* prod = &plus->arg2() << Product::builder();
ok

2022-11-17 10:24 UTC, zh-qs commented on engine/src/Symbol/Product.cu
> +        Reciprocal* rec = &prod->arg2() << Reciprocal::builder();
ok

2022-11-17 10:25 UTC, zh-qs commented on engine/src/Symbol/Polynomial.cu
> +    }
to prawda

2022-11-17 10:31 UTC, zh-qs commented on engine/src/Symbol/Polynomial.cu
> +    std::string Polynomial::to_tex() const { // TODO popraw!
ok

2022-11-17 10:45 UTC, zh-qs commented on engine/src/Symbol/Polynomial.cu
> +                                                            Symbol* const destination) {
ok

2022-11-17 10:48 UTC, zh-qs commented on engine/src/Symbol/Product.cuh
> +    __host__ __device__ bool try_simplify_polynomials(Symbol* const help_space);
Słusznie, "simplify" sugeruje skracanie przez NWD

2022-11-17 10:51 UTC, zh-qs commented on engine/src/Symbol/Product.cuh
> +    __host__ __device__ bool try_simplify_polynomials(Symbol* const help_space);
Zmieniłem nazwę, poprawiłem też opis funkcji

2022-11-17 13:25 UTC, zh-qs commented on engine/src/Symbol/Symbol.cuh
> +        __host__ __device__ double get_monomial_coefficient(Symbol* const help_space) const;
Dodałem strukturę `OptionalNumber` z działaniami arytmetycznymi (żeby w `Symbol.cu` nie było cały czas sprawdzania `hsa_value()`)

2022-11-17 13:26 UTC, zh-qs commented on engine/src/Symbol/Macros.cuh
> +    DEFINE_IS_NOT_MONOMIAL
ok, przeniosłem wszystko do funkcji `is_polynomial` i `get_monomial_coefficients`

2022-11-17 14:48 UTC, szymon-zygula approved these changes

2022-11-17 14:48 UTC, merged