About screen
Cusymint/cusymint pull request #89
Opened 2022-11-12 19:57 UTC by TortillaZHawaii

Closes #69

2022-11-16 09:00 UTC, zh-qs commented on front/cusymint_l10n/assets/translations/pl.json
> +    "aboutText": "Cusymint zostało zainspirowane wykłedem o sztucznej inteligencji wykładanym na MIT przez profesora Patricka H. Winstona. Cusymint różni się od typowych kalkulatorów symbolicznych. P
1. zainspirowane wykłedem -> zainspirowane wykładem
2. Wziąłbym całą nazwę przedmiotu "Projekt badawczy - algorytmy na GPU" w cudzysłów, bo jest ona dość długa i myląca jeśli chodzi o czytanie
3. Wydaje mi się, że tytuły naukowe można zamienić na skróty prof. i dra, tak jak w wersji angielskiej

2022-11-16 09:03 UTC, zh-qs commented on front/cusymint_ui/lib/src/organisms/authors_widget.dart
> +    'Krzysztof Kaczmarski'
Kaczmarski chyba nie jest autorem tego projektu

2022-11-16 09:06 UTC, TortillaZHawaii commented on front/cusymint_ui/lib/src/organisms/authors_widget.dart
> +    'Krzysztof Kaczmarski'
Na wykładzie z programowania zespołowego mówił, że będzie miło promotorowi jak go się umieści jako autora.

2022-11-16 09:22 UTC, zh-qs commented on front/cusymint_ui/lib/src/templates/about_template.dart
> +      body: Center(
Brakuje tu drawera, tak jak w pozostałych template'ach

2022-11-16 09:24 UTC, zh-qs commented on front/cusymint_ui/lib/src/organisms/authors_widget.dart
> +    'Krzysztof Kaczmarski'
W takim razie zróbmy dobry uczynek XD

2022-11-16 09:37 UTC, zh-qs requested changes
Najbardziej z tym drawerem jest problem, bo ikonka nie rysuje się taka, jak powinna (strzałka), i przycisk zamiast pokazywać drawer jak w innych ekranach po prostu sobie wraca do poprzedniego

2022-11-16 10:10 UTC, TortillaZHawaii commented on front/cusymint_ui/lib/src/templates/about_template.dart
> +      body: Center(
Specjalnie go nie wrzucałem. Zazwyczaj w takich ekranach umożliwia się tylko powrót. Imo z opcji też by się przydało zabrać Drawer.
Przykład z Google Maps:
<p>
<img src="https://user-images.githubusercontent.com/62249621/202151884-98591ef8-e36c-4e08-b8dd-a6ad93a009f6.png" width="200/>

<img src="https://user-images.githubusercontent.com/62249621/202151900-3aabe141-0883-406a-9809-27b111f43aac.png" width="200"/>
</p>

2022-11-16 10:41 UTC, zh-qs commented on front/cusymint_ui/lib/src/templates/about_template.dart
> +      body: Center(
To sugeruję zrobić tak, żeby z `about` wracało do strony, a nie do drawera

2022-11-16 16:26 UTC, TortillaZHawaii commented on front/cusymint_ui/lib/src/templates/about_template.dart
> +      body: Center(
Poprawione 🤠

2022-11-17 09:49 UTC, zh-qs approved these changes

2022-11-17 09:49 UTC, merged