Metaoperatory `Same` i `PatternPair`
Cusymint/cusymint pull request #93
Opened 2022-11-14 13:19 UTC by zh-qs

Kolejny stopień świadomości metaoperatorów. Teraz, używając operatora `Same`, można sprawdzać, czy dwa wyrażenia są identyczne (np. `Add<Same, Inv<Same>>::match` sprawdzi, czy wyrażenie jest postaci `coś+1/coś`). Dodałem też pomocniczy operator `PatternPair` z funkcją `match_pair`, która pozwala sprawdzać jednocześnie dwa wyrażenia według podanego wzoru (`Same` też tu działa; przykłady użycia są np. w pliku `Addition.cu`)

2022-11-14 14:26 UTC, szymon-zygula requested changes

2022-11-14 14:26 UTC, szymon-zygula commented on engine/src/Symbol/MetaOperators.cuh
> +        __host__ __device__ static bool match(const Symbol& dst, const Symbol& other) {
`other` bym nazwał może `other_same`, w innych metaoperatorach `other` nie mówi zbytnio, czym to właściwie jest i że ma związek z `Same`.

2022-11-14 14:26 UTC, szymon-zygula commented on engine/src/Symbol/MetaOperators.cuh
> +        static constexpr bool HasSame = false;
`HasSame` powinno się nazywać `HAS_SAME`, bo jest to stała, a nie typ

2022-11-14 16:02 UTC, zh-qs commented on engine/src/Symbol/MetaOperators.cuh
> +        static constexpr bool HasSame = false;
Inne stałe, jak np. `TwoArgOperator::LAdditionalArgsSize` też mają takie nazwy i tym się zasugerowałem, zmienić także te zgodnie z konwencją, co napisałeś?

2022-11-14 21:01 UTC, szymon-zygula commented on engine/src/Symbol/MetaOperators.cuh
> +        static constexpr bool HasSame = false;
Tak, powinny być wszystkie UPPER_CASE jak w innych częściach projektu

2022-11-15 07:49 UTC, zh-qs commented on engine/src/Symbol/MetaOperators.cuh
> +        static constexpr bool HasSame = false;
zrobiłem

2022-11-15 21:18 UTC, szymon-zygula approved these changes

2022-11-15 21:18 UTC, merged